# Generated by Django 5.0.3 on 2024-03-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminis',
            name='Checked',
        ),
    ]
